import LegalLayout, {
  BulletList,
  Callout,
  ContactBlock,
  InfoGrid,
  Section,
  TocItem,
} from "@/components/legal/LegalLayout";

const TOC: TocItem[] = [
  { id: "introduction", label: "1. Introduction" },
  { id: "data-collection", label: "2. Data We Collect" },
  { id: "how-we-use", label: "3. How We Use Your Data" },
  { id: "data-sharing", label: "4. Data Sharing" },
  { id: "ai-training", label: "5. AI & Model Training" },
  { id: "data-retention", label: "6. Data Retention" },
  { id: "security", label: "7. Security" },
  { id: "your-rights", label: "8. Your Rights" },
  { id: "cookies", label: "9. Cookies" },
  { id: "contact", label: "10. Contact Us" },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout
      pageTitle="Privacy Policy"
      title="Privacy Policy"
      description="We take your privacy seriously. This policy explains what data we collect, how we use it, and the choices you have over your information."
      effectiveDate="March 1, 2025"
      lastUpdated="March 1, 2026"
      tocItems={TOC}
      canonicalPath="/legal/privacy-policy"
    >
      <Section id="introduction" number={1} title="Introduction">
        <p>
          SkillScout (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;)
          operates an AI-powered mock interview and job-readiness platform. This
          Privacy Policy describes how we collect, use, disclose, and safeguard
          your information when you use our website and Service.
        </p>
        <p>
          By using SkillScout, you consent to the data practices described in
          this policy. If you do not agree, please discontinue use of the
          Service.
        </p>
      </Section>

      <Section id="data-collection" number={2} title="Data We Collect">
        <p>
          We collect information you provide directly, data generated by your
          use of the Service, and certain technical data automatically.
        </p>
        <InfoGrid
          items={[
            {
              icon: "badge",
              title: "Identity Data",
              description:
                "Name, email address, professional title, and profile photo.",
            },
            {
              icon: "mic",
              title: "Audio & Video Data",
              description:
                "Voice and optional video recordings captured during mock interview sessions.",
            },
            {
              icon: "description",
              title: "Résumé Content",
              description:
                "Work experience, education, skills, and certifications parsed from uploaded résumés.",
            },
            {
              icon: "analytics",
              title: "Performance Analytics",
              description:
                "Interview scores, answer quality metrics, improvement trends, and weak-area heatmaps.",
            },
            {
              icon: "work",
              title: "Job Preferences",
              description:
                "Target roles, seniority levels, preferred industries, and salary expectations.",
            },
            {
              icon: "devices",
              title: "Technical Data",
              description:
                "IP address, browser type, device identifiers, and session logs.",
            },
          ]}
        />
      </Section>

      <Section id="how-we-use" number={3} title="How We Use Your Data">
        <p>We use your data to:</p>
        <BulletList
          items={[
            "Deliver personalised AI mock interview sessions and real-time feedback.",
            "Generate detailed performance reports and skill-gap analyses.",
            "Match you with relevant job roles using our Job Matching Engine.",
            "Send transactional messages: invoices, password resets, and security alerts.",
            "Improve platform reliability, performance, and AI accuracy.",
            "Comply with legal obligations and enforce our Terms of Service.",
          ]}
        />
      </Section>

      <Section id="data-sharing" number={4} title="Data Sharing">
        <p>
          We do not sell your personal data. We may share limited information
          with:
        </p>
        <BulletList
          items={[
            "Cloud infrastructure providers (e.g., AWS) necessary to operate the Service — under strict data processing agreements.",
            "Payment processors to complete subscription transactions — we share only what is required.",
            "Analytics providers for aggregate, anonymised product usage insights.",
            "Law enforcement or regulatory authorities where required by applicable law.",
          ]}
        />
        <Callout type="warning" title="Recruiter Disclosure">
          If you choose to share your SkillScout profile or interview report
          with a recruiter via our platform, that information will be visible to
          them. You control this sharing at all times from your account
          settings.
        </Callout>
      </Section>

      <Section id="ai-training" number={5} title="AI & Model Training">
        <p>
          SkillScout uses AI to power our interview simulation, feedback engine,
          and job-matching features. We are transparent about how we handle your
          data in relation to AI:
        </p>
        <Callout type="success" title="Default: No AI Training on Your Data">
          Your personal interview recordings, résumé, and performance data are
          NOT used to train our public or foundational AI models by default. All
          AI processing in real-time sessions is strictly for generating your
          personal feedback report.
        </Callout>
        <p className="mt-4">
          You may optionally opt-in to contribute anonymised interaction data to
          improve future AI quality. This opt-in is always voluntary and can be
          revoked from your privacy settings at any time.
        </p>
      </Section>

      <Section id="data-retention" number={6} title="Data Retention">
        <p>
          We retain your personal data for as long as your account is active or
          as needed to provide the Service. Specific retention windows:
        </p>
        <BulletList
          items={[
            "Interview recordings: retained for 90 days, then automatically deleted unless you choose to save them.",
            "Performance analytics: retained for the life of your account.",
            "Résumé uploads: retained until you delete them from your profile.",
            "Account data: retained for 30 days after account deletion, then permanently purged.",
            "Billing records: retained for 7 years to satisfy financial regulations.",
          ]}
        />
      </Section>

      <Section id="security" number={7} title="Security">
        <p>
          We implement industry-standard security measures to protect your
          information:
        </p>
        <InfoGrid
          items={[
            {
              icon: "lock",
              title: "Encryption",
              description:
                "All data in transit is encrypted via TLS 1.3; data at rest is encrypted using AES-256.",
            },
            {
              icon: "verified_user",
              title: "Access Controls",
              description:
                "Strict role-based access ensures only authorised personnel can access personal data.",
            },
            {
              icon: "security",
              title: "Vulnerability Management",
              description:
                "Regular penetration testing and automated scanning of our infrastructure.",
            },
            {
              icon: "backup",
              title: "Data Backups",
              description:
                "Automated daily backups with point-in-time recovery to prevent data loss.",
            },
          ]}
        />
        <p className="mt-4">
          Despite our measures, no transmission over the internet is 100%
          secure. Please use a strong password and enable two-factor
          authentication.
        </p>
      </Section>

      <Section id="your-rights" number={8} title="Your Rights">
        <p>
          Depending on your location, you may have the following rights
          regarding your personal data:
        </p>
        <BulletList
          items={[
            "Access: request a copy of the personal data we hold about you.",
            "Correction: request correction of inaccurate or incomplete data.",
            "Deletion: request deletion of your account and associated personal data.",
            "Portability: receive your interview reports and analytics in a machine-readable format.",
            "Restriction: request that we restrict processing of your data in certain circumstances.",
            "Objection: object to processing based on legitimate interests.",
          ]}
        />
        <p>
          To exercise any of these rights, contact us at{" "}
          <a
            href="mailto:privacy@skillscout.ai"
            className="text-primary underline"
          >
            privacy@skillscout.ai
          </a>
          . We will respond within 30 days.
        </p>
      </Section>

      <Section id="cookies" number={9} title="Cookies">
        <p>
          We use cookies and similar tracking technologies to operate and
          improve the Service. Types of cookies we use:
        </p>
        <BulletList
          items={[
            "Essential cookies: required for authentication, session management, and core platform functionality.",
            "Analytics cookies: help us understand how users interact with the platform (anonymised).",
            "Preference cookies: remember your settings such as dark mode and notification preferences.",
          ]}
        />
        <p>
          You can control cookies through your browser settings. Disabling
          essential cookies may affect platform functionality.
        </p>
      </Section>

      <Section id="contact" number={10} title="Contact Us">
        <p>
          If you have questions, concerns, or requests relating to this Privacy
          Policy, please contact our Data Privacy team:
        </p>
        <ContactBlock email="privacy@skillscout.ai" />
      </Section>
    </LegalLayout>
  );
}
